//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 

using System.Xml.Serialization;

namespace HartStone.LinqClasses {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class CardDefs {
        
        private CardDefsEntity[] itemsField;
        
        /// <remarks/>
        [XmlElement("Entity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CardDefsEntity[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class CardDefsEntity {
        
        private string masterPowerField;
        
        private CardDefsEntityTag[] tagField;
        
        private CardDefsEntityReferencedTag[] referencedTagField;
        
        private CardDefsEntityPower[] powerField;
        
        private CardDefsEntityEntourageCard[] entourageCardField;
        
        private CardDefsEntityTriggeredPowerHistoryInfo[] triggeredPowerHistoryInfoField;
        
        private string versionField;
        
        private string cardIDField;
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MasterPower {
            get {
                return this.masterPowerField;
            }
            set {
                this.masterPowerField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("Tag", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public CardDefsEntityTag[] Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("ReferencedTag", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CardDefsEntityReferencedTag[] ReferencedTag {
            get {
                return this.referencedTagField;
            }
            set {
                this.referencedTagField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("Power", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CardDefsEntityPower[] Power {
            get {
                return this.powerField;
            }
            set {
                this.powerField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("EntourageCard", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CardDefsEntityEntourageCard[] EntourageCard {
            get {
                return this.entourageCardField;
            }
            set {
                this.entourageCardField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("TriggeredPowerHistoryInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CardDefsEntityTriggeredPowerHistoryInfo[] TriggeredPowerHistoryInfo {
            get {
                return this.triggeredPowerHistoryInfoField;
            }
            set {
                this.triggeredPowerHistoryInfoField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string CardID {
            get {
                return this.cardIDField;
            }
            set {
                this.cardIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class CardDefsEntityTag {
        
        private string enumIDField;
        
        private string typeField;
        
        private string valueField;
        
        private string valueField1;
        
        /// <remarks/>
        [XmlAttribute()]
        public string enumID {
            get {
                return this.enumIDField;
            }
            set {
                this.enumIDField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField1;
            }
            set {
                this.valueField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class CardDefsEntityReferencedTag {
        
        private string nameField;
        
        private string enumIDField;
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string enumID {
            get {
                return this.enumIDField;
            }
            set {
                this.enumIDField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class CardDefsEntityPower {
        
        private CardDefsEntityPowerPlayRequirement[] playRequirementField;
        
        private string definitionField;
        
        /// <remarks/>
        [XmlElement("PlayRequirement", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CardDefsEntityPowerPlayRequirement[] PlayRequirement {
            get {
                return this.playRequirementField;
            }
            set {
                this.playRequirementField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string definition {
            get {
                return this.definitionField;
            }
            set {
                this.definitionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class CardDefsEntityPowerPlayRequirement {
        
        private string reqIDField;
        
        private string paramField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string reqID {
            get {
                return this.reqIDField;
            }
            set {
                this.reqIDField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string param {
            get {
                return this.paramField;
            }
            set {
                this.paramField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class CardDefsEntityEntourageCard {
        
        private string cardIDField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string cardID {
            get {
                return this.cardIDField;
            }
            set {
                this.cardIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class CardDefsEntityTriggeredPowerHistoryInfo {
        
        private string effectIndexField;
        
        private string showInHistoryField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string effectIndex {
            get {
                return this.effectIndexField;
            }
            set {
                this.effectIndexField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string showInHistory {
            get {
                return this.showInHistoryField;
            }
            set {
                this.showInHistoryField = value;
            }
        }
    }
}
