//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HartStone {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HartStone.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Dbf&gt;
        ///	&lt;Column name=&quot;ID&quot; type=&quot;Int&quot; comment=&quot;primary key&quot; /&gt;
        ///	&lt;Column name=&quot;NOTE_MINI_GUID&quot; type=&quot;String&quot; comment=&quot;client-side card name&quot; /&gt;
        ///	&lt;Column name=&quot;IS_COLLECTIBLE&quot; type=&quot;Bool&quot; comment=&quot;show in collection manager?&quot; /&gt;
        ///	&lt;Column name=&quot;HERO_POWER_ID&quot; type=&quot;Int&quot; comment=&quot;ASSET.CARD.ID of the hero power used by this card&quot; /&gt;
        ///	&lt;Column name=&quot;LONG_GUID&quot; type=&quot;String&quot; /&gt;
        ///	&lt;Column name=&quot;CRAFTING_EVENT&quot; type=&quot;String&quot; comment=&quot;when can this card be crafted or disenchanted?&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CARD {
            get {
                return ResourceManager.GetString("CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Dbf&gt;
        ///	&lt;Column name=&quot;ID&quot; type=&quot;Int&quot; /&gt;
        ///	&lt;Column name=&quot;NOTE_DESC&quot; type=&quot;String&quot; /&gt;
        ///	&lt;Column name=&quot;DATA1&quot; type=&quot;Long&quot; /&gt;
        ///	&lt;Column name=&quot;SOURCE&quot; type=&quot;String&quot; /&gt;
        ///	&lt;Column name=&quot;SORT_CATEGORY&quot; type=&quot;Int&quot; /&gt;
        ///	&lt;Column name=&quot;SORT_ORDER&quot; type=&quot;Int&quot; /&gt;
        ///	&lt;Column name=&quot;NAME&quot; type=&quot;LocString&quot; /&gt;
        ///	&lt;Column name=&quot;NAME_COMMENT&quot; type=&quot;String&quot; /&gt;
        ///	&lt;Column name=&quot;DESCRIPTION&quot; type=&quot;LocString&quot; /&gt;
        ///	&lt;Column name=&quot;SOURCE_DESCRIPTION&quot; type=&quot;LocString&quot; /&gt;
        ///	&lt;Column name=&quot;ENABLED&quot; type=&quot;Bool&quot; /&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CARD_BACK {
            get {
                return ResourceManager.GetString("CARD_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CardDefs&gt;
        ///  &lt;Entity version=&quot;2&quot; CardID=&quot;CS1h_001&quot;&gt;
        ///    &lt;MasterPower&gt;5f0999b3-52fd-4382-90d4-296de2994e34&lt;/MasterPower&gt;
        ///    &lt;Tag enumID=&quot;185&quot; type=&quot;String&quot;&gt;Geringe Heilung&lt;/Tag&gt;
        ///    &lt;Tag enumID=&quot;183&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;202&quot; type=&quot;&quot; value=&quot;10&quot; /&gt;
        ///    &lt;Tag enumID=&quot;201&quot; type=&quot;&quot; value=&quot;3&quot; /&gt;
        ///    &lt;Tag enumID=&quot;199&quot; type=&quot;&quot; value=&quot;6&quot; /&gt;
        ///    &lt;Tag enumID=&quot;203&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;48&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;251&quot; type=&quot;&quot; value=&quot;1&quot; /&gt;
        ///    &lt;Tag enumID=&quot;184&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string deDE {
            get {
                return ResourceManager.GetString("deDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CardDefs&gt;
        ///  &lt;Entity version=&quot;2&quot; CardID=&quot;CS1h_001&quot;&gt;
        ///    &lt;MasterPower&gt;5f0999b3-52fd-4382-90d4-296de2994e34&lt;/MasterPower&gt;
        ///    &lt;Tag enumID=&quot;185&quot; type=&quot;String&quot;&gt;Lesser Heal&lt;/Tag&gt;
        ///    &lt;Tag enumID=&quot;183&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;202&quot; type=&quot;&quot; value=&quot;10&quot; /&gt;
        ///    &lt;Tag enumID=&quot;201&quot; type=&quot;&quot; value=&quot;3&quot; /&gt;
        ///    &lt;Tag enumID=&quot;199&quot; type=&quot;&quot; value=&quot;6&quot; /&gt;
        ///    &lt;Tag enumID=&quot;203&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;48&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;251&quot; type=&quot;&quot; value=&quot;1&quot; /&gt;
        ///    &lt;Tag enumID=&quot;184&quot; type [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string enGB {
            get {
                return ResourceManager.GetString("enGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CardDefs&gt;
        ///  &lt;Entity version=&quot;2&quot; CardID=&quot;CS1h_001&quot;&gt;
        ///    &lt;MasterPower&gt;5f0999b3-52fd-4382-90d4-296de2994e34&lt;/MasterPower&gt;
        ///    &lt;Tag enumID=&quot;185&quot; type=&quot;String&quot;&gt;Lesser Heal&lt;/Tag&gt;
        ///    &lt;Tag enumID=&quot;183&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;202&quot; type=&quot;&quot; value=&quot;10&quot; /&gt;
        ///    &lt;Tag enumID=&quot;201&quot; type=&quot;&quot; value=&quot;3&quot; /&gt;
        ///    &lt;Tag enumID=&quot;199&quot; type=&quot;&quot; value=&quot;6&quot; /&gt;
        ///    &lt;Tag enumID=&quot;203&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;48&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;251&quot; type=&quot;&quot; value=&quot;1&quot; /&gt;
        ///    &lt;Tag enumID=&quot;184&quot; type [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string enUS {
            get {
                return ResourceManager.GetString("enUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CardDefs&gt;
        ///  &lt;Entity version=&quot;2&quot; CardID=&quot;CS1h_001&quot;&gt;
        ///    &lt;MasterPower&gt;5f0999b3-52fd-4382-90d4-296de2994e34&lt;/MasterPower&gt;
        ///    &lt;Tag enumID=&quot;185&quot; type=&quot;String&quot;&gt;Sanación inferior&lt;/Tag&gt;
        ///    &lt;Tag enumID=&quot;183&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;202&quot; type=&quot;&quot; value=&quot;10&quot; /&gt;
        ///    &lt;Tag enumID=&quot;201&quot; type=&quot;&quot; value=&quot;3&quot; /&gt;
        ///    &lt;Tag enumID=&quot;199&quot; type=&quot;&quot; value=&quot;6&quot; /&gt;
        ///    &lt;Tag enumID=&quot;203&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;48&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;251&quot; type=&quot;&quot; value=&quot;1&quot; /&gt;
        ///    &lt;Tag enumID=&quot;184 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string esES {
            get {
                return ResourceManager.GetString("esES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CardDefs&gt;
        ///  &lt;Entity version=&quot;2&quot; CardID=&quot;CS1h_001&quot;&gt;
        ///    &lt;MasterPower&gt;5f0999b3-52fd-4382-90d4-296de2994e34&lt;/MasterPower&gt;
        ///    &lt;Tag enumID=&quot;185&quot; type=&quot;String&quot;&gt;Sanación inferior&lt;/Tag&gt;
        ///    &lt;Tag enumID=&quot;183&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;202&quot; type=&quot;&quot; value=&quot;10&quot; /&gt;
        ///    &lt;Tag enumID=&quot;201&quot; type=&quot;&quot; value=&quot;3&quot; /&gt;
        ///    &lt;Tag enumID=&quot;199&quot; type=&quot;&quot; value=&quot;6&quot; /&gt;
        ///    &lt;Tag enumID=&quot;203&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;48&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;251&quot; type=&quot;&quot; value=&quot;1&quot; /&gt;
        ///    &lt;Tag enumID=&quot;184 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string esMX {
            get {
                return ResourceManager.GetString("esMX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CardDefs&gt;
        ///  &lt;Entity version=&quot;2&quot; CardID=&quot;CS1h_001&quot;&gt;
        ///    &lt;MasterPower&gt;5f0999b3-52fd-4382-90d4-296de2994e34&lt;/MasterPower&gt;
        ///    &lt;Tag enumID=&quot;185&quot; type=&quot;String&quot;&gt;Soins inférieurs&lt;/Tag&gt;
        ///    &lt;Tag enumID=&quot;183&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;202&quot; type=&quot;&quot; value=&quot;10&quot; /&gt;
        ///    &lt;Tag enumID=&quot;201&quot; type=&quot;&quot; value=&quot;3&quot; /&gt;
        ///    &lt;Tag enumID=&quot;199&quot; type=&quot;&quot; value=&quot;6&quot; /&gt;
        ///    &lt;Tag enumID=&quot;203&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;48&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;251&quot; type=&quot;&quot; value=&quot;1&quot; /&gt;
        ///    &lt;Tag enumID=&quot;184&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string frFR {
            get {
                return ResourceManager.GetString("frFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CardDefs&gt;
        ///  &lt;Entity version=&quot;2&quot; CardID=&quot;CS1h_001&quot;&gt;
        ///    &lt;MasterPower&gt;5f0999b3-52fd-4382-90d4-296de2994e34&lt;/MasterPower&gt;
        ///    &lt;Tag enumID=&quot;185&quot; type=&quot;String&quot;&gt;Cura Inferiore&lt;/Tag&gt;
        ///    &lt;Tag enumID=&quot;183&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;202&quot; type=&quot;&quot; value=&quot;10&quot; /&gt;
        ///    &lt;Tag enumID=&quot;201&quot; type=&quot;&quot; value=&quot;3&quot; /&gt;
        ///    &lt;Tag enumID=&quot;199&quot; type=&quot;&quot; value=&quot;6&quot; /&gt;
        ///    &lt;Tag enumID=&quot;203&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;48&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;251&quot; type=&quot;&quot; value=&quot;1&quot; /&gt;
        ///    &lt;Tag enumID=&quot;184&quot; t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string itIT {
            get {
                return ResourceManager.GetString("itIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CardDefs&gt;
        ///  &lt;Entity version=&quot;2&quot; CardID=&quot;CS1h_001&quot;&gt;
        ///    &lt;MasterPower&gt;5f0999b3-52fd-4382-90d4-296de2994e34&lt;/MasterPower&gt;
        ///    &lt;Tag enumID=&quot;185&quot; type=&quot;String&quot;&gt;하급 치유&lt;/Tag&gt;
        ///    &lt;Tag enumID=&quot;183&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;202&quot; type=&quot;&quot; value=&quot;10&quot; /&gt;
        ///    &lt;Tag enumID=&quot;201&quot; type=&quot;&quot; value=&quot;3&quot; /&gt;
        ///    &lt;Tag enumID=&quot;199&quot; type=&quot;&quot; value=&quot;6&quot; /&gt;
        ///    &lt;Tag enumID=&quot;203&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;48&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;251&quot; type=&quot;&quot; value=&quot;1&quot; /&gt;
        ///    &lt;Tag enumID=&quot;184&quot; type=&quot;Stri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string koKR {
            get {
                return ResourceManager.GetString("koKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CardDefs&gt;
        ///  &lt;Entity version=&quot;2&quot; CardID=&quot;CS1h_001&quot;&gt;
        ///    &lt;MasterPower&gt;5f0999b3-52fd-4382-90d4-296de2994e34&lt;/MasterPower&gt;
        ///    &lt;Tag enumID=&quot;185&quot; type=&quot;String&quot;&gt;Pomniejsze uzdrowienie&lt;/Tag&gt;
        ///    &lt;Tag enumID=&quot;183&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;202&quot; type=&quot;&quot; value=&quot;10&quot; /&gt;
        ///    &lt;Tag enumID=&quot;201&quot; type=&quot;&quot; value=&quot;3&quot; /&gt;
        ///    &lt;Tag enumID=&quot;199&quot; type=&quot;&quot; value=&quot;6&quot; /&gt;
        ///    &lt;Tag enumID=&quot;203&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;48&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;251&quot; type=&quot;&quot; value=&quot;1&quot; /&gt;
        ///    &lt;Tag enumID [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string plPL {
            get {
                return ResourceManager.GetString("plPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CardDefs&gt;
        ///  &lt;Entity version=&quot;2&quot; CardID=&quot;CS1h_001&quot;&gt;
        ///    &lt;MasterPower&gt;5f0999b3-52fd-4382-90d4-296de2994e34&lt;/MasterPower&gt;
        ///    &lt;Tag enumID=&quot;185&quot; type=&quot;String&quot;&gt;Cura Inferior&lt;/Tag&gt;
        ///    &lt;Tag enumID=&quot;183&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;202&quot; type=&quot;&quot; value=&quot;10&quot; /&gt;
        ///    &lt;Tag enumID=&quot;201&quot; type=&quot;&quot; value=&quot;3&quot; /&gt;
        ///    &lt;Tag enumID=&quot;199&quot; type=&quot;&quot; value=&quot;6&quot; /&gt;
        ///    &lt;Tag enumID=&quot;203&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;48&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;251&quot; type=&quot;&quot; value=&quot;1&quot; /&gt;
        ///    &lt;Tag enumID=&quot;184&quot; ty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ptBR {
            get {
                return ResourceManager.GetString("ptBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CardDefs&gt;
        ///  &lt;Entity version=&quot;2&quot; CardID=&quot;CS1h_001&quot;&gt;
        ///    &lt;MasterPower&gt;5f0999b3-52fd-4382-90d4-296de2994e34&lt;/MasterPower&gt;
        ///    &lt;Tag enumID=&quot;185&quot; type=&quot;String&quot;&gt;Малое исцеление&lt;/Tag&gt;
        ///    &lt;Tag enumID=&quot;183&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;202&quot; type=&quot;&quot; value=&quot;10&quot; /&gt;
        ///    &lt;Tag enumID=&quot;201&quot; type=&quot;&quot; value=&quot;3&quot; /&gt;
        ///    &lt;Tag enumID=&quot;199&quot; type=&quot;&quot; value=&quot;6&quot; /&gt;
        ///    &lt;Tag enumID=&quot;203&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;48&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;251&quot; type=&quot;&quot; value=&quot;1&quot; /&gt;
        ///    &lt;Tag enumID=&quot;184&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ruRU {
            get {
                return ResourceManager.GetString("ruRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CardDefs&gt;
        ///  &lt;Entity version=&quot;2&quot; CardID=&quot;CS1h_001&quot;&gt;
        ///    &lt;MasterPower&gt;5f0999b3-52fd-4382-90d4-296de2994e34&lt;/MasterPower&gt;
        ///    &lt;Tag enumID=&quot;185&quot; type=&quot;String&quot;&gt;次级治疗术&lt;/Tag&gt;
        ///    &lt;Tag enumID=&quot;183&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;202&quot; type=&quot;&quot; value=&quot;10&quot; /&gt;
        ///    &lt;Tag enumID=&quot;201&quot; type=&quot;&quot; value=&quot;3&quot; /&gt;
        ///    &lt;Tag enumID=&quot;199&quot; type=&quot;&quot; value=&quot;6&quot; /&gt;
        ///    &lt;Tag enumID=&quot;203&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;48&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;251&quot; type=&quot;&quot; value=&quot;1&quot; /&gt;
        ///    &lt;Tag enumID=&quot;184&quot; type=&quot;Stri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string zhCN {
            get {
                return ResourceManager.GetString("zhCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CardDefs&gt;
        ///  &lt;Entity version=&quot;2&quot; CardID=&quot;CS1h_001&quot;&gt;
        ///    &lt;MasterPower&gt;5f0999b3-52fd-4382-90d4-296de2994e34&lt;/MasterPower&gt;
        ///    &lt;Tag enumID=&quot;185&quot; type=&quot;String&quot;&gt;次級治療術&lt;/Tag&gt;
        ///    &lt;Tag enumID=&quot;183&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;202&quot; type=&quot;&quot; value=&quot;10&quot; /&gt;
        ///    &lt;Tag enumID=&quot;201&quot; type=&quot;&quot; value=&quot;3&quot; /&gt;
        ///    &lt;Tag enumID=&quot;199&quot; type=&quot;&quot; value=&quot;6&quot; /&gt;
        ///    &lt;Tag enumID=&quot;203&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;48&quot; type=&quot;&quot; value=&quot;2&quot; /&gt;
        ///    &lt;Tag enumID=&quot;251&quot; type=&quot;&quot; value=&quot;1&quot; /&gt;
        ///    &lt;Tag enumID=&quot;184&quot; type=&quot;Stri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string zhTW {
            get {
                return ResourceManager.GetString("zhTW", resourceCulture);
            }
        }
    }
}
